default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff
        args:
          - --fix
          - --config
          - ruff.toml
      - id: ruff-format
        args:
          - --config
          - ruff.toml

  - repo: local
    hooks:
      - id: ty-check
        name: ty check
        entry: uv run --frozen ty check
        language: system
        types: [python]
        pass_filenames: false
